documentTitle: "オリオンシステム：CLI駆動型構成ファイル Ver. 3.0"
systemConfig:
  version: "3.0"
  description: "このファイルはorion-calendar-importerサービスに特化した設定を管理します。"

# Configuration specific to the calendar importer service
calendar_importer_config:
  # List of Google Calendar IDs to import events from.
  calendar_ids:
    - 'primary' # The primary calendar of the authenticated user (机長)
    - 'monex.co.jp_2mh9q2t746223opi90ck2d3a0o@group.calendar.google.com' # (すべて)経済指標カレンダー
    - 'monex.co.jp_hkslb9v1kj95se5r8ag2mms4k8@group.calendar.google.com' # 米国市場休場日カレンダー
    - 'monex.co.jp_vm8hs3tiu5cp7gdlk04bla79o0@group.calendar.google.com'  # （重要）経済指標カレンダー
