# Orion System - Hardened CI/CD Pipeline
# This configuration enforces per-service identity and secure, authenticated deployments.
steps:
  # --------------------------------------------------------------------
  # Service: orion-sec-fetcher (Cloud Run Service)
  # --------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build orion-sec-fetcher'
    dir: 'microservices/orion-sec-fetcher'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-sec-fetcher:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push orion-sec-fetcher'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-sec-fetcher:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy orion-sec-fetcher'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'orion-sec-fetcher'
      - '--image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-sec-fetcher:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--service-account=orion-sec-fetcher-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated' # Enforce IAM-based authentication
      - '--project=$PROJECT_ID'

  # --------------------------------------------------------------------
  # Service: orion-insight-wrangler (Cloud Run Service)
  # --------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build orion-insight-wrangler'
    dir: 'microservices/orion-insight-wrangler'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-insight-wrangler:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push orion-insight-wrangler'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-insight-wrangler:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy orion-insight-wrangler'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'orion-insight-wrangler'
      - '--image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-insight-wrangler:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--service-account=orion-insight-wrangler-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated' # Enforce IAM-based authentication
      - '--project=$PROJECT_ID'

  # --------------------------------------------------------------------
  # Service: zero-cost-filter (Cloud Function)
  # --------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy zero-cost-filter'
    entrypoint: 'gcloud'
    dir: 'microservices/zero-cost-filter'
    args:
      - 'functions'
      - 'deploy'
      - 'zero-cost-filter'
      - '--gen2'
      - '--runtime=python312'
      - '--source=.'
      - '--entry-point=pre_filter_url'
      - '--trigger-topic=raw-urls-ingest'
      - '--region=asia-northeast1'
      - '--service-account=zero-cost-filter-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--project=$PROJECT_ID'

  # --------------------------------------------------------------------
  # Service: trigger-alpha-loop-func (Cloud Function)
  # --------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy trigger-alpha-loop-func'
    entrypoint: 'gcloud'
    dir: 'microservices/alpha-loop-launcher'
    args:
      - 'functions'
      - 'deploy'
      - 'trigger-alpha-loop-func'
      - '--gen2'
      - '--runtime=python312'
      - '--source=.'
      - '--entry-point=main'
      - '--trigger-http'
      - '--no-allow-unauthenticated' # Enforce IAM-based authentication
      - '--region=asia-northeast1'
      - '--service-account=trigger-alpha-loop-func-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--project=$PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 200
