# Orion System - Final CI/CD Dispatcher Pipeline
steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'Fetch git history'
  entrypoint: 'bash'
  args: [ '-c', 'git fetch --unshallow' ]

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Identify and deploy changed services'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | xargs -n 1 dirname | sort -u)
    for dir in $${CHANGED_DIRS}; do
      if [ "$$dir" == "." ]; then continue; fi
      if [ -f "$${dir}/cloudbuild.yaml" ]; then
        echo "--> Triggering build for '$${dir}'"
        gcloud builds submit "$${dir}" \
          --config="$${dir}/cloudbuild.yaml" \
          --substitutions=_COMMIT_SHA=$COMMIT_SHA,_PROJECT_ID=$PROJECT_ID \
          --project=$PROJECT_ID
      fi
    done

options:
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 200