steps:
# ... (previous steps remain the same) ...

# Deploy orion-insight-wrangler with more memory
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'orion-insight-wrangler',
    '--image', '...',
    '--memory', '512Mi', # Increased memory
    # ... (other args)
  ]

# Deploy orion-job-sentiment-analyzer with more memory
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'functions', 'deploy', 'orion-job-sentiment-analyzer',
    '--memory', '512Mi', # Increased memory
    # ... (other args)
  ]

# Deploy orion-synergy-analyzer with more memory
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'functions', 'deploy', 'orion-synergy-analyzer',
    '--memory', '512Mi', # Increased memory
    # ... (other args)
  ]