steps:
# ... (previous steps for orion-sec-fetcher and orion-options-analyzer remain the same) ...

# 5. Deploy orion-daily-heartbeat as a Cloud Run service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-daily-heartbeat:latest', './microservices/orion-daily-heartbeat']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-daily-heartbeat:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'orion-daily-heartbeat',
    '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-daily-heartbeat:latest',
    '--region', 'asia-northeast1',
    '--service-account', 'orion-service-account@$PROJECT_ID.iam.gserviceaccount.com',
    '--no-allow-unauthenticated',
    '--set-env-vars=GCP_PROJECT=$PROJECT_ID,REPORTING_AGENT_URL=https://orion-reporting-agent-328258682114.asia-northeast1.run.app'
  ]

images:
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-sec-fetcher:latest'
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-options-analyzer:latest'
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-daily-heartbeat:latest'