steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-sec-fetcher:latest', './microservices/orion-sec-fetcher']

# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-sec-fetcher:latest']

# 3. Deploy the container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'orion-sec-fetcher',
    '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-sec-fetcher:latest',
    '--region', 'asia-northeast1',
    '--service-account', 'orion-service-account@$PROJECT_ID.iam.gserviceaccount.com',
    '--no-allow-unauthenticated',
    '--set-env-vars=GCP_PROJECT=$PROJECT_ID'
  ]

images:
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/orion-images/orion-sec-fetcher:latest'