# Orion System - Final CI/CD Dispatcher Pipeline
# This pipeline identifies changed microservices and triggers their specific builds.
steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'Fetch git history'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Cloud Build performs a shallow clone. We need more history to diff against the previous commit.
    git fetch --unshallow

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Identify and deploy changed services'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Get a list of directories that have changed compared to the previous commit.
    CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | xargs -n 1 dirname | sort -u)

    echo "===================================================="
    echo "Changed directories detected: $${CHANGED_DIRS}"
    echo "===================================================="

    for dir in $${CHANGED_DIRS}; do
      # Skip the root directory to prevent recursive builds.
      if [ "$$dir" == "." ]; then
        echo "--> Change detected in root directory, skipping trigger."
        continue
      fi

      # Check if a cloudbuild.yaml exists in the changed directory, indicating it's a deployable service.
      if [ -f "$${dir}/cloudbuild.yaml" ]; then
        echo "--> Change detected in '$${dir}', triggering build..."
        gcloud builds submit "${dir}" \
          --config="${dir}/cloudbuild.yaml" \
          --substitutions=_COMMIT_SHA=$COMMIT_SHA \
          --project=$PROJECT_ID
      else
        echo "--> Change detected in '$${dir}', but no cloudbuild.yaml found. Skipping."
      fi
    done

    echo "All changed services have been processed."

options:
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 200