# Service-specific pipeline for orion-job-sentiment-analyzer
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: 
    - 'functions'
    - 'deploy'
    - 'orion-job-sentiment-analyzer'
    - '--gen2'
    - '--runtime=python312'
    - '--source=.'
    - '--entry-point=analyze_job_sentiment'
    - '--trigger-event-filters=type=google.cloud.storage.object.v1.finalized'
    - '--trigger-event-filters=bucket=orion-hr-jobs-storage' # Assuming this is the bucket name
    - '--region=asia-northeast1'
    - '--service-account=job-sentiment-analyzer-sa@$_PROJECT_ID.iam.gserviceaccount.com'
