macro_analyzer_config:
  fred_series_ids:
    - M2SL
    - DFF
    - DGS10
  market_symbols:
    - ^IXIC
  ai_prompt: |
    あなたはシニアマクロ経済アナリストです。以下の**過去のデータ**と**未来の予定**を統合的に分析してください。

    ## 分析対象データ1：過去の市場相関
    以下の相関行列は、過去2年間の主要経済指標と市場の相関関係を示しています。
    - M2 Money Supply (M2SL): 通貨供給量
    - Federal Funds Effective Rate (DFF): 政策金利
    - 10-Year Treasury Constant Maturity Rate (DGS10): 10年債利回り
    - Gold Futures (GC=F): ゴールド価格
    - NASDAQ Composite (^IXIC): 市場ベンチマーク

    ```
    {correlation_matrix}
    ```

    ## 分析対象データ2：未来の経済イベント
    今後30日間に、以下の重要イベントが予定されています。
    ```
    {events_string}
    ```

    ## 指示
    上記2つの情報を基に、以下の項目について、プロフェッショナルな視点から簡潔なインサイトを生成してください。
    1.  **現在の市場センチメント:** 過去の相関関係と、未来のイベント（例：金利発表）を考慮して、現在の市場がリスクオンかリスクオフかを評価せよ。
    2.  **注目すべきイベントと相関:** 今後予定されているイベントの中で、現在の相関関係を大きく変化させる可能性のあるイベントはどれか。その理由も述べよ。
    3.  **ポートフォリオへの戦略的示唆:** このマクロ環境と今後のイベントが、テクノロジー株中心のポートフォリオに与える短期的な影響（追い風か、逆風か）を予測し、具体的な戦略的推奨を述べよ。