# Service-specific pipeline for trigger-alpha-loop-func
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy'
  entrypoint: 'gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'trigger-alpha-loop-func'
    - '--gen2'
    - '--runtime=python312'
    - '--source=.'
    - '--entry-point=launch_alpha_loop_job_v2'
    - '--trigger-http'
    - '--no-allow-unauthenticated'
    - '--region=asia-northeast1'
    - '--service-account=trigger-alpha-loop-func-sa@$PROJECT_ID.iam.gserviceaccount.com'
    - '--project=$PROJECT_ID'
