options_analyzer_config:
  ai_prompt: |
    あなたは市場のセンチメント分析の専門家です。以下のデータを分析してください。

    1.  **市場全体のセンチメント（参考指標）:**
        - CBOE Total Put/Call Ratio: {cboe_pc_ratio}

    2.  **個別ポートフォリオ銘柄のニュースセンチメント (Finnhub News Sentiment Score):**
        (スコアは-1.0が最も弱気、1.0が最も強気を示す)
        {portfolio_news_sentiment}

    この分析に基づき、以下の項目について、プロフェッショナルな視点から簡潔なインサイトを生成してください。
    1.  **現在の市場全体のセンチメント評価:** CBOEのP/Cレシオから、市場全体が「強気」「弱気」「中立」のいずれの状態にあるか評価せよ。
    2.  **注目すべき個別銘柄センチメント:** Finnhubのニュースセンチメントスコアが特に高い（強気）または低い（弱気）銘柄を指摘し、その背景を推察せよ。
    3.  **ポートフォリオへの戦略的示唆:** このセンチメント分析が、我々のテクノロジー株中心のポートフォリオに与える短期的な影響（追い風か、逆風か、あるいは特定の銘柄への警告か）。
